### ISSUE TITLE
use markdown

### ISSUE THREAD

**Issue by christian-fei** [joebew42/joebew42.github.io#1]
hello joe, what do you think of using the `.md`  extension for your notes?
since your are already using the basic forms of the format, you just need to change the extension :)

This would be helpful for reading your notes on github or with a dedicated client

**Comment by joebew42** [comment]
Hi Christian, thank you for your observation! I'll reorganize all the notes in markdown format during the next days.

**Comment by joebew42** [comment]
@christian-fei I have done some tests on my local machine, I encountered some difficulties in accessing `.md` files directly from browser. Chrome, for example, is asking me to download the file instead of showing contents directly. Here is the question:
- How can I easily read `.md` file contents from browser ?

I'm thinking that the notes can be easily converted in `jekyll`posts. What do you think ? I should run `daily-activity-log` next to `jekyll` as notes manager.

**Comment by christian-fei** [comment]
hmmm, that's true, i look up your notes from github.. Didn't think about the case, although on my browser (Chrome, mac) the file is simply showed, without being downloaded..

With `include` directive of the Jekyll configuration file `_config.yml` you should be able to process them without having to move your notes folder..
http://jekyllrb.com/docs/configuration/

**Comment by christian-fei** [comment]
I would not introduce jekyll at this point, it wouldn't make much sense..

**Comment by christian-fei** [comment]
what you could do is link to the github preview instead:
E.g. [kanban notes](https://github.com/joebew42/joebew42.github.io/blob/master/notes/20150611kanban.txt)

**Comment by joebew42** [comment]
@christian-fei But if we add links to a github URL we are tying the feature of reading log contents (`notes/`) with an external service. Should be great if contents like notes or whatever is part of the daily activity log can be accessed in off-line mode too (i.e. *.txt, *.md, *.ogg, *.ogv). I should be able to move my daily activity log from one host to another while keeping intact access to the contents.

Maybe a fine tuned Jekyll configuration can solve this kind of problem. For example, a URL pointing to `notes/2015/08/05/title-here` should work in both offline and online ways, maybe with different behaviour (i.e. well formatted in online mode if we use tool like Jekyll and raw content in offline mode), while the access to the resource holds.

What do you think ?

**Comment by christian-fei** [comment]
good point
